basePath: /api/v1
definitions:
  handlers.Response:
    properties:
      data: {}
      status:
        type: integer
      timestamp:
        type: string
      version:
        type: string
    type: object
  model.Client:
    type: object
host: localhost:8080
info:
  contact: {}
  description: Client resource module. Manages manually typed and compiled online
    data of prospective clients
  title: client-factpack/clients
  version: "1.0"
paths:
  /createProfile:
    post:
      consumes:
      - application/json
      description: Create new client profile, given the populated json
      parameters:
      - description: Client data
        in: body
        name: client
        required: true
        schema:
          $ref: '#/definitions/model.Client'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handlers.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Create Clients
      tags:
      - clients
  /health:
    get:
      description: Basic health check
      produces:
      - application/json
      responses:
        "200":
          description: Connection status
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: ping
      tags:
      - health
  /retrieveAllProfiles:
    get:
      description: Retrieve all client data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.Client'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Get All Clients
      tags:
      - clients
  /retrieveProfile:
    get:
      description: Retrieve client data by profile id
      parameters:
      - description: Hex id used to identify client
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/handlers.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Client'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.Response'
      summary: Get Client By ID
      tags:
      - clients
swagger: "2.0"
