// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PrefectServiceInterface is an autogenerated mock type for the PrefectServiceInterface type
type PrefectServiceInterface struct {
	mock.Mock
}

// TriggerPrefectFlowRun provides a mock function with given fields: deploymentID, apiKey, params
func (_m *PrefectServiceInterface) TriggerPrefectFlowRun(deploymentID string, apiKey string, params map[string]interface{}) error {
	ret := _m.Called(deploymentID, apiKey, params)

	if len(ret) == 0 {
		panic("no return value specified for TriggerPrefectFlowRun")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]interface{}) error); ok {
		r0 = rf(deploymentID, apiKey, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPrefectServiceInterface creates a new instance of PrefectServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrefectServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrefectServiceInterface {
	mock := &PrefectServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
