// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PrefectFlowRunnerInterface is an autogenerated mock type for the PrefectFlowRunnerInterface type
type PrefectFlowRunnerInterface struct {
	mock.Mock
}

// Trigger provides a mock function with given fields: deploymentID, params
func (_m *PrefectFlowRunnerInterface) Trigger(deploymentID string, params map[string]interface{}) error {
	ret := _m.Called(deploymentID, params)

	if len(ret) == 0 {
		panic("no return value specified for Trigger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(deploymentID, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPrefectFlowRunnerInterface creates a new instance of PrefectFlowRunnerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrefectFlowRunnerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrefectFlowRunnerInterface {
	mock := &PrefectFlowRunnerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
