basePath: /api/v1
definitions:
  models.StatusRes:
    properties:
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Authentication service for managing auth flows
  title: client-factpack/auth
  version: "1.0"
paths:
  /auth/confirmForgetPassword:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Submit Cognito OTP sent to user's email to proceed with password
        reset
      parameters:
      - example: ABCDEF
        in: formData
        name: code
        type: string
      - example: "67890"
        in: formData
        name: newPassword
        type: string
      - example: joel.ow.2022
        in: formData
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatusRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusRes'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.StatusRes'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.StatusRes'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StatusRes'
      summary: Confirm Forget Password
      tags:
      - auth
  /auth/createUser:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Admin registers user with Cognito user pool via email and password
      parameters:
      - description: User's email address
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatusRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusRes'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.StatusRes'
      summary: Create Users
      tags:
      - auth
  /auth/forgetPassword:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Forget password
      parameters:
      - example: joel.ow.2022
        in: formData
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatusRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusRes'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.StatusRes'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.StatusRes'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StatusRes'
      summary: Forget Password
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Cognito SSO login using username and password
      parameters:
      - example: "12345"
        in: formData
        name: password
        type: string
      - example: joel.ow.2022
        in: formData
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.StatusRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.StatusRes'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.StatusRes'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/models.StatusRes'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.StatusRes'
      summary: Login
      tags:
      - auth
  /health:
    get:
      description: Basic health check
      produces:
      - application/json
      responses:
        "200":
          description: Connection status
          schema:
            $ref: '#/definitions/models.StatusRes'
      summary: ping
      tags:
      - health
swagger: "2.0"
